default: &default
  database: 'auth_gateway'
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: auth_gateway_test

production:
  <<: *default
